#####################################################
# OpsMx AutoPilot and Integrated Spinnaker Delivery
# This file contains configurations for AP as well as Spinnaker
#####################################################


# Global variables can be accessed across all the charts including sub-charts
global:
  # when this flag is set to false; UI will be accessible over http instead of https
  ssl:
    enabled: true
  
  gitea:
    enabled: true
    standardrepoBranch: 3.12
    admin:
      existingSecret: gitea-secret
      username: opsmx
      password: opsmxadmin123
  # If cert-manager is installed, TLS secrets will created automatically, as an 'Issuer' will be created
  # Else, the TLS secrets will need to created manually

  # Common gate for both spin and oes services. Change ONLY if required
  commonGate:
    spinnakerRBAC: true  # Set to true if RBAC is enabled in Spinnaker


  ## OES-UI url configuration
  oesUI:
    protocol: https
    host: isd.prod.opsmx.net
    # Use below port when hostname above is an external IP instead of a hostname
    #port: 31466

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: oes-ui-ingress

#####################################################
# Spinnaker instance configuration
#####################################################
spinnaker:
  gitopsHalyard:
    enabled: true
    secretName: opsmx-gitops-auth  # No need to change this
    repo:
      type: git # git, s3, stash(bitbucket server) use a different sample values file for s3/bitbuck-stash
      baseUrlHostName: github.com    # Specify the Base FQDN of your repository without the protocol
      organization: OpsMx
      projectName: ""                # Specify project name only if repo is under a project
      repository: test-repo # repo name for GitOps Halyard (Sample Reference: https://github.com/OpsMx/sample-gitops-repo.git).
      halConfigBranch: master # Branch under which halyard config is present under above repository
      halConfigPath: / #relative path from repository root folder
      username: userx  # Username to authenticate with git/stash repo
      token: passx  # Token corresponding to above username
      ## kubectl create secret generic ssh-secret --from-file=ssh --from-file=known_hosts -n <namespace> 
      ## please make sure the rsa key is present in file called ssh and known host for the github.com present in known_hosts file
      ## ssh-keyscan github.com >> ~/.ssh/known_hosts
      ## Configure below fields only if repo type is s3
    pipelinePromotion:  # GitHub only,  Not supportd on S3 or Stash
      enabled: false
###############################################################################################
###############################################################################################
#### The values below this line are best not changed except in rare situations
###############################################################################################
###############################################################################################
## Name of the secret for pulling images from container registry.
## Use it when the images are stored under private registry.
## Create this secret before installing the chart
imagePullSecret: "opsmx11-secret"
